Revert "Roll AppRTC 3168981..e7f6cae"
This reverts commit bb14af8a299248d1471d4cfc5b63922297665fea in
https://codereview.chromium.org/1509873002/

Reason: collider fails to build:
________ running '/usr/bin/python webrtc.DEPS/build_apprtc_collider.py' in '/mnt/data/b/build/slave/Linux_Builder/build'
src/out/go-workspace/src/collider/collider.go:55: undefined: tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
src/out/go-workspace/src/collider/collider.go:59: undefined: tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Traceback (most recent call last):
  File "webrtc.DEPS/build_apprtc_collider.py", line 43, in <module>
    sys.exit(main())
  File "webrtc.DEPS/build_apprtc_collider.py", line 38, in main
    env=golang_env)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go/bin/go', 'get', 'collidermain']' returned non-zero exit status 2
Error: Command '/usr/bin/python webrtc.DEPS/build_apprtc_collider.py' returned non-zero exit status 1 in /mnt/data/b/build/slave/Linux_Builder/build

BUG=567598
TBR=phoglund@chromium.org

Review URL: https://codereview.chromium.org/1508853004 .